on: workflow_dispatch
name: Publish to Test PyPI
jobs:
  publish-testpypi:
    name: Upload release to Test PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/p/trackhub
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        pip install build
        python -m build --sdist
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
