name: test
on: [push]

jobs:
  conda-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -e
          eval "$(conda shell.bash hook)"
          conda create -p ./test-env -y --file requirements.txt --file test-requirements.txt --channel conda-forge --channel bioconda
          source activate ./test-env
          python setup.py install
          pytest -vv --doctest-modules trackhub
          cd doc && make doctest html
          conda deactivate
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: doc/build/html
  pip-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py sdist
      - run: pip install dist/*.tar.gz
      - run: python -c 'import trackhub'
