name: test
on: [push]
defaults:
  run:
    shell: bash -l {0}

jobs:
  conda-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          eval "$(conda shell.bash hook)"
          conda create -p ./test-env -y --file requirements.txt --file test-requirements.txt --channel conda-forge --channel bioconda
          source activate ./test-env
          pytest -vv --doctest-modules trackhub
          conda deactivate
  pip-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python setup.py sdist
      - run: pip install dist/*.tar.gz
      - run: python -c 'import trackhub'

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: conda activate ./test-env
      - run: cd docs && make html

  push-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        ...
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
