name: test
on: [push]
jobs:
  conda-env:
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v2
      - run: conda install -y --file requirements.txt pytest sphinx
      - run: pytest -vv --doctest-modules trackhub
