name: test
on: [push]
defaults:
  run:
    shell: bash -l {0}

jobs:
  conda-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          conda create -p ./test-env -y --file requirements.txt --file test-requirements.txt --channel conda-forge --channel bioconda
          source activate ./test-env
          pytest -vv --doctest-modules trackhub
          conda deactivate
